[project]
name = "flow-twinx"
version = "0.8.0"
description = "A terminal music player with online and offline modes sourced from youtube."
readme = "README.md"
requires-python = ">=3.14"
dynamic = []
dependencies = [
    "dbus-fast>=5.0.22",
    "dbus-python>=1.4.0",
    "flask",
    "numpy",
    "psutil>=7.2.2",
    "pygobject>=3.58.0",
    "python-vlc",
    "questionary",
    "sounddevice",
    "textual>=8.2.8",
    "yt-dlp>=2026.8.19",
    "ytmusicapi",
]

[project.scripts]
flow = "cli.main:main"
flow-tui = "tui:main"
flow-web = "web.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cli*", "backend*", "tui*", "web*"]

[tool.setuptools.package-data]
flow_twinx = ["Hyprland/*.qml"]
web = ["templates/*"]

[dependency-groups]
dev = [
    "pyinstaller>=6.21.0",
    "textual-dev>=1.8.0",
    "pytest>=8.0",
]
temp = [
    "pyside6>=6.11.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
